### ISSUE TITLE
Perform an APIM dry run with dependencies

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/release#129] opened 2020-09-24 16:26 UTC
# Description

Perform a `dry run` release of APIM for components with SNAPSHOT dependencies. 
We need a common maven repo to store all "fake" artifacts to manage a full dryrun.
Perhaps there's a way to share a maven repo between different jobs.

# Validation

* [ ] on the release repo, manually start a dry run, all SNAPSHOTS repo will run a dry run job with the real maven dry run

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-09-26 12:18
* A Circle CI piepline is completely defined with a yaml file `.circleci/config.yml`, and : 
  * A Circle CI Pipeline is made of workflows, 
  * A Circle CI Pipeline Workflow, is made of jobs
  * A Circle CI Pipeline job is made of steps
  * A Set of Circle CI Pipeline steps executes sequentially, and its order of execution is defined by the content of  the 
`.circleci/config.yml` file
  * A Set of Circle CI Pipeline jobs can be forced to execute sequentially, and if so its order of execution is defined by the content of  the `.circleci/config.yml` file.
  * Changing the execution order of a set of Jobs or steps requires to edit the `.circleci/config.yml` file.
* Without a server, there is no way any file can be transfered from one Pipeline, to another.
* The above listed properties of Circle CI are pretty much the same for all CI CD solutions I know of, because by design, a Pipeline "is somethign that executes a task", designed to execute with managed performance (to manage the global consumption of the whole platform resources, whether an OpenStack or a Kubernetes Cluster, or a mesos, or a swarm). 
* For security reasons, pipelines are not servers, therefore there will never ever be any pipeline to which you directly upload files to, which is why to transfer files from one pipeline `P1`, to another, `P2` there will always be just one way to do it :
  * download the files from `P1`  
  * then upload the files to a server `SomeServer`
  * and when `P2` starts its execution, it will download the files from `SomeServer`
  * also note that Pipelines are always designed to not ever be a server, because the date/time when the execution of a given pipeline is by nature unpredictable:
    * Because one cannot predict at all times, how many people will request a pipeline execution, and the resources are always limited
    * Even when a Pipeline, for example Circle CI, is set to execute as a cron job, the time at which it will actually start executing, is un predictible, it just guarantees the time when it will enter the "pending" state : waiting fro resources to be available in order to actually start its execution. 
* For all those reasons, the only way to share files between "all the jobs executing releases for all components", would be to write one `.circleci/config.yml` "where evertyhing happens",
* For Each dry run release, the `release.json` can a have an un-predictable number of `components` with suffix `-SNAPSHOT` : 
  * so if we do want a different job for every component in the `release.json` : 
    * we would have to write a `.circelci/config.yml` which has as many jobs as there are `components` in the `release.json`
    * and would require to edit the `.circleci/config.yml` everytime a component is added or deleted from the `release.json`
  * and if we choose to execute the release (dry run or not) of all components in the same job, then we are back to the pattern where we have to git clone all of them and carry out the release of all of them inside the same job : I understood this was a rejeted option.
* Finally, if we were to set up a server, to share files between job, and those jobs are maven operations on those files : 
  * I feel like saying that it is exactly what a Maven Central repository does, and I doubt we can do better than what people who worked on maven the last 20 years did
  * Well if we have to set up a server, let it be a maven central repository

This is why I think that to perform a release, in a multi-repo context, there is no quicker, and better way than doing that using a Maven Central Repository : 
* Now the question is : 
  * do we use One server for dry runs, and another for "true releases" ? 
  * that's the only question I can see, and I would add one requirement : that performing a dry run should not require modifying anything in the pom.xml, or any file versioned in all components repo, (except maven server config), or it's not a dry run anymore. Dry run is running an operation on one thing that should be the exact same thing when "not in dry run".
* For all those reasons, I think that to perform a dry run, the most simple way is to use 2 different servers : 
  * the "dry run maven central server", does not need a lot of resources, it can be small, because we can completely flush it (empty it), between two dry runs.

For "not dry run releases", well there is at least one server which has to have a lot of storage : at least one, which we can trust "it will not loose our assets (jars), and keep them in high availability for all the customers to use it anytime in production environments. 

Al in all, I there fore think the quickest way to perform dry run is to use a server, a maven central repository, which does not need to be big, or highly available, just at reasonably available, so dry run do not constantly keep failing because of that server.

 to give a order of idea : I set up on AWS an EC2 instance with one pulblic IP (EIP), Elasticsearch and MongoDB, which has been used by my tests on pulumi EKS Fargate, and used by one of our Customers, recently:  
 * cost  less than 60 dollars in September 2020.
* The EC2 instance never ever let me down even once, And I used used it a lot
* so if someone manages such an insance for us, shoudl be just as reliable, and cost les than 60 dollars a month
* and if we manage our own EC2 instance and provision our maven central there : well it's not uncommon a thing to do for CICD guys... Plus we already have a docker setup ready as I understood.

I understand that managing an EC2 instance of our own, is something we will have to avoid: well then I do not disagree, and I'd say it is a good reason to invest money there. Not a lot of money, since we do not need a lot of storage, for that dry run. 

I also want to add I advocate separate Maven Central Repositories for dryn run release, and "non-dry run releases" : 
* to avoid management complexity (not to have to be careful to not interfere with "real products for customers")
* and mostly too, because if we use same service fro many things, it will necessarily end being a beast : will have many requirements, for many different uses, will require a lot of resources, will be a single point of failure, etc.. etc...

I am not against using an EC2 instance with a maven central repository, that e manage ourselves, for dry runs : 
* OVH VM are known to be like so unreliable compared to EC2 
* there are ways to manage infrastructure issues I heard of, in other companies, like loosing SSH connection etc, very quick and very standard ways : 
  * use Infrastructure as code : 
     * when I loose the SSH Key cannot SSH connect or any complicated problem shows up
     * hey its the dry run server, i dont care loosing all data, so I : 
      * terraform destroy / terraform apply again,
       * secrethub write the new SSH Key : anyone who is allowed  to uses secrethub read to get the SSH Key again 
       * problem solved
     * actualy i'll do that with `pulumi` : even faster, and can run in a Circle CI Pipeline.

So conclusion : managing infrastructure can be done much more reliably than what was seen in a partner company, and rose fear (simple OVH instace etc..), and if we don't want to manage infrastructure (less work for me, just fine) , then we need to pay people t do it for us. Little money, it's just one little server for dry runs.

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-09-26 12:23
Note I will need to ask questions, to understand difference between : 
* running a dry run with, or without `-SNAPSHOT`
* my first two questions are : 
  * Am I right if say both are just a job running `maven` commands ?
  * only diferences between the two, are in the maven commands ? (running with, or without `SNAPSHOT` is just about changing maven commands)

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-10-30 14:34
# About the ability to share files, between different pipelines

In [this above comment](https://github.com/gravitee-io/release/issues/129#issuecomment-699488201) , I have extensively analyzed what would involve, sharing files between two different Circle CI pipelines : by different, I mean that those 2 Pipelines are related to 2 different github.com git repositories

My analysis came to the the conclusion : 
* that it is technically impossible, due to the very nature of a Pipeline, to achieve such a file sharing,  without using a server, of any kind.
* that since Maven central repositories are, the best design that the world industry could today come up with, of a server to share java artifacts, it is very unlikely, that there exists any feature of Circle CI making it possible, to share files between different Pipelines. 

To complete this analysis of the problem, and verify the conclusion I came to, i will now  list all search queries and results I could think of, to find other people talking about trying to achieve that (sharing files between pipelines).


### Search results

* Search 1 / Google `circleci share files between pipelines`  : 
  * 
  


# Caching strategy for a given pipeline

Circle CI V2 has caching capabilities, regarding files generated and used : 
* inside the same pipeline, across different jobs
* inside the same pipeline, across 2 different pipeline executions

Those capabilities are well documented here : https://circleci.com/docs/2.0/caching/

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-10-30 18:02
so conclusion is that to perform a dry run, we will use a maven central repository : 
* tear down and setup before any dry run
* so that anytime, its the latest dry run in the maven central repo dedicated to dry-runs 

todo : 
* [ ] clear doc of secret management for all cicd system initialization
* [ ] take in account fixed repos list gien by @NicolasGeraud on slack for deployment scope of pipeline definition (some are not in `release.json`)
* [ ] begin automation with clever cloud artifactory to mvn deploy artifacts : 
  * orb modifications ? 
  * relying on `settings.xml` to configure maven central repo , and exact artifact repo in artifactory 
  * no one uses the artifactory service, verified, so safe to play with

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-10-30 19:01
# LAST UPDATE AND TEST ON GRAVITEE LAB BEFORE FINAL MOVE TO GRVITEE-IO

the git operation to perform at the end of all maven releases (dry run or not dry run)




# pattern idea for non dry run releases and infra

problem initiating idea : transaction to publish to public nexus sonatype is very long, so should be shoved out of the way of a cicd process



idea kept for the true release : 
* cron scheduled pipeline to sync true release artifactory and the public sonatype .
* all  artifactory maven central repos used in the flow of cicd processes are private : they are the source of truth to publish artifacts to public maven repos

same pattern for future packages et

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-11-06 16:02
## Configuration of the Clever Cloud Artifactory on dry run `mvn clean deploy`

* key configuration points to use the jfrog maven plugin :  
  * https://github.com/gravitee-lab/jfrog-activation-guardian/blob/e58174bd35999ab20f1b897f545168e7fd8144cd/guard-shift/pom.xml#L65 : 
    * this one has to be turned into a `settings.xml` , where repository, plugins, pluginsRepository and jfrog maven plugin properties (username / password) have to be factorized 
   * the `settings.xml` will the be better off managed a one secret file, holding all of that config  
  * I will validate the settings.xml configuration using a fork of https://github.com/gravitee-lab/jfrog-activation-guardian

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-11-09 00:19
I believe that there is no possiblity ot define the remote repository URL using the `settings.xml`. It is required, that this conifiguration is set into the pom.xml of the maven project itself, or a parent pom. In our case, that's going to be the `gravitee-parent` : 
* So I think we will need to fork the gravitee-parent, and create a dry-gravitee-parent
* or better I think is to create a new maven profile in `gravitee-parent` (won't impact any maven project since none of them will use that profile) : 
  * add a dry run maven profile redifining distribution management, and run the clean deploy with the `mvn -P dry-run` option.
  * I can test that option by : 
    * forking and modifying the gravitee-parent into gravitee-lab, and mvn clean deploy it to clever cloud artifactory see https://github.com/gravitee-lab/gravitee-parent/blob/17.x/pom.xml and https://github.com/gravitee-lab/clever-cloud-artifactory-deployment-prototype/tree/GRAVTEE_PARENT_MVN_PROFILE
    * changing the pom.xml of the gravitee-common repositories to resolve gravitee-parent from clever cloud artifactory in https://github.com/gravitee-lab/clever-cloud-artifactory-deployment-prototype

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-11-09 04:44
finally, I think the gravitee-parent should be included in the `release.json` as a dependency,and it will be released with every dry run, when marked as `-SNAPSHOT`, just like any other dependency

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-11-09 05:34
note that I have stripped out of the `-P gravitee-dry-run-release` maven profile, a few plugins : 
* the plugin including sources into the jar :  I had an issue with it, Array out of bound, perhaps because in the gravitee-parent, well, there is no Java source ode at all...
* the gpg sign : the issue I experienced was simple, I had no private signing  key. Note that wie will have this problem for the non-dry run release, so we will have to create secrets for the gpg signing key. This plugin can ertainly be restore even in the dry run process.
* the `nexus-staging-maven-plugin` : this one we cerainly will not nee him, and will remain stripped out of the dry run maven profile
* Which left me with just one maven plugin, the enforcer plugin. Okmaeks sesne. Good thing.

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-11-09 10:29
* [ ] test the `altDeploymentRepository` after I removed all `distributionManagement` into gravitee-parent https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html. Beware dversion 3+ for deploy plugin
*

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-11-18 01:45
During today's tests : 
* it becomes clear, that all maven tests which launch a server, are a problem (they cannot run inside a pripeline
* And i found one case where a compoenent is requring antoher, but, in `-SNAPSHOT` version, so there must be some kind of maven update version process there (remove the -SNAPSHOT mentions from the depencies, or there is something I do not understand yet). the case is [this pipeline execution](https://app.circleci.com/pipelines/github/gravitee-lab/gravitee-management-rest-api/122/workflows/85f635af-639c-42aa-8bbf-b6d670881a18/jobs/138)

So many llttle problems around, detcted, but they have to do with the workflow process, the dry run globally works, and works real good.

## A new Orchestrator FEature : Resume Exeution plan and persistence

I have one new idea though : 
* Say I have started a release and release 11 components out of 25, 
* Well then I would like to resume the release, skipping all components which have already been released in the dependency tree
* this would require that the orchestration / dependency tree state has to be stored,  between two orchestrator executions : 
  * the git commit id of the https://github.com/gravitee-io/release repo identifies the release which has to be resumed
  * the pipeline execution GUID identifies the orchestrator executions for one GIT COMMIT ID of the release repo
  * this is why the orchestrator needs to store a state for the execution plan, which is a tree. Everytime a component 's pipeline execution ends up with success, the sucess state ahs to be persisted.
   * and every time the orchestrator starts, it first goes and checks in its database, if a release with the same GIT COMMIT ID (from the release repo) has already been started), to resume the execution state.
* that's why I definitely think there should be

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-11-18 13:15
also note that I had to skip tests to be able to maven release the gravitee components

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-11-18 17:17
* [ ] finish artifactory pure management : make all gravitee components resolve all dependencies from artifactory ONLY, and it should work fetching dependencies from nexus, with artifactory as a proxy of the nexus central
* [ ] and then must fix the execution of tests, removing the `-D skipTests=true`  options from `Orb`
* [ ] the resume feature with `release.json` updated with successfully released

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-11-19 01:10
* ok, I now configured the maven private artifactory repository to resolv dependencies : https://app.circleci.com/pipelines/github/gravitee-lab/gravitee-repository/8/workflows/ef1e1cef-9147-46a4-9d75-c9305db35f48/jobs/8
* Now the repository to configure should be configured in artifactory, to mirror nexus : 
  * the gravitee parent pom is there: https://odbxikk7vo-artifactory.services.clever-cloud.com/webapp/#/artifacts/browse/tree/General/nexus-mirror/io/gravitee/gravitee-parent/17.1 and there http://odbxikk7vo-artifactory.services.clever-cloud.com/nexus-mirror/io/gravitee/gravitee-parent/17.1/
  * but the pipeline keepsgetinga403 error from http://odbxikk7vo-artifactory.services.clever-cloud.com/nexus-mirror/ although I gave read permissions to the graviteebot artifactory user

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-11-19 05:23
Nowtrying to define mutilple mirrors, sounds like not that obvious in maven... well,astonishing since this is quite a common use case I believe, ... NErvermind, references on the subject : 
* https://stackoverflow.com/questions/16257306/maven-settings-for-multiple-mirrors

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-11-19 07:12
NowI have an issue downloading antoher depenedency, `jackson-...-asl`,but I tested I can download no problemusing the credentials used in the pipeline :

```bash
# total success with both of those curls : 

# ---> trace
curl -u "${ARTIFACTORY_BOT_USER_NAME}:${ARTIFACTORY_BOT_USER_PWD}" http://odbxikk7vo-artifactory.services.clever-cloud.com/remote-nexus-cache/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13-javadoc.jar?trace

# ----> actual download of the file : 
curl -u "${ARTIFACTORY_BOT_USER_NAME}:${ARTIFACTORY_BOT_USER_PWD}" -O http://odbxikk7vo-artifactory.services.clever-cloud.com/remote-nexus-cache/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13-javadoc.jar
# And noprb, I got the `jackson-mapper-asl-1.9.13-javadoc.jar` file locally 
```

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-11-19 07:34
previous issue on jackson-something-asl is solved, and now I have the same error, but with antoher : 

```bash 
curl -u "${ARTIFACTORY_BOT_USER_NAME}:${ARTIFACTORY_BOT_USER_PWD}" http://odbxikk7vo-artifactory.services.clever-cloud.com/nexus-and-dry-run-releases/org/apache/commons/commons-io/1.3.2/commons-io-1.3.2.pom?trace
```

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-11-25 22:11
All dependencies are now pulled from the private artifactory serivce, and artifacts are deployed to the same private artifactory service. I validated this configuration using the `-DskipTests=true` configuration, to all maven command executions.

Now, We nee to make sure all tests are executed prior to any release :  All release must be guaranted by these tests. 
As I removed the `-DskipTests=true` configuration, I could identitfy a first issue, to run the tests : 
* all the maven commands are executed using a docker contianer (the official docker library maven image)
* the user executing the maven commands in the container is the `root` user
* but some tests, like those spawing up a postgres database, fail because the user running the commands in the docker container, is the `root` user.
* So I have to make usre a non-root user,whatever it is, runs the maven commands in the docker container : 
  * this is why I had to manufacture a gravitee.io custom docker image from the official maven docker image
  * running the maven commands requires using at least one docker volume, to"slip the source code of the gravitee component in the docker container". This is why the uid and gid of the user running maven commands in the docker container, must match the uid and gid of the user outsitde the maven docker container, which git clones the gravitee component's source code (the `circleci` user, in the Circle CI Pipeline executor).

Doing that, I encountered some problems about file permission, a very classic problem. 

Do solve out those file permissions issues, I automated the build and push of the gravitee maven docker image (used in the `gravitee-io/gravitee@1.0.x` Circle CI Orb), with a Circle CI Pipeline,  and added a test phase, to test the built docker image before it is published, for use in the Gravtiee Components Pipelines.

In that tests phase, I basically tests all possible use cases of the docker image. I among things, tested there reproducing the file permissions issue I experienced with the Circle CI Orb.

I here keep a few references of the executions of that test phase, to reproduce my file permissions issue : 
* https://app.circleci.com/pipelines/github/gravitee-lab/GraviteeCiCdOrchestrator/764/workflows/07440a74-695b-46e9-8484-6369ccd26e87/jobs/552 : 8 different tests are executed, the 8tgh test executes successfully (without reproducing the issue), the exact same command as in the CircleCI Orb, where I experience the issue : the command is `mvn -Duser.home=/home/circleci/ -s ./settings.xml -B -U -P gravitee-dry-run clean test`

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-11-26 17:52
Docker container with non-root user issues are now all solved. While I tested that, I encountered 2 issues, which are not CICD issues : 
* `gravitee-management-rest-api` failed to compile, which is probably explained by a git context in the https://github.com/gravitee-lab test environment (repos needs to be forked again, all at the same time, so that some classes are not missing across git repositories). It also threw an error, in the tests phase, the following for the record :

```bash
Running io.gravitee.rest.api.fetcher.FetcherConfigurationFactoryTest
17:20:59.942 [main] ERROR io.gravitee.rest.api.fetcher.impl.FetcherConfigurationFactoryImpl - Unable to create a Fetcher configuration from a null or empty configuration data
17:20:59.950 [main] ERROR io.gravitee.rest.api.fetcher.impl.FetcherConfigurationFactoryImpl - Unable to create a Fetcher configuration from a null or empty configuration data
17:21:00.108 [main] ERROR io.gravitee.rest.api.fetcher.impl.FetcherConfigurationFactoryImpl - Unable to instance Fetcher configuration for io.gravitee.rest.api.fetcher.DummyFetcherConfiguration
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "value2" (class io.gravitee.rest.api.fetcher.DummyFetcherConfiguration), not marked as ignorable (2 known properties: "value", "filepath"])
 at [Source: (String)"{
  "value": 123,
  "value2": "chunked"
}"; line: 3, column: 14] (through reference chain: io.gravitee.rest.api.fetcher.DummyFetcherConfiguration["value2"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:843)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1206)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
```

* `gravitee-management-webui` was missing a proper configuration for the maven license plugin, in the `pom.xml`. A proper configuration to run the Pipeline commands, requires the `<exclude>.*/**</exclude>` entry in the configuration of the maven license plugin in the `pom.xml`. For the record, the maven license plugin configuration in the `pom.xml` of the `gravitee-management-webui` Gravitee Component was reset, on all git branches, to: 

```Xml
      <plugin>
        <groupId>com.mycila</groupId>
        <artifactId>license-maven-plugin</artifactId>
        <configuration>
          <mapping>
            <ts>SLASHSTAR_STYLE</ts>
          </mapping>
          <excludes>
            <exclude>LICENSE.txt</exclude>
            <exclude>node/**</exclude>
            <exclude>node_modules/**</exclude>
            <exclude>src/libraries/**</exclude>
            <exclude>**/*.scss</exclude>
            <exclude>**/*.svg</exclude>
            <exclude>Jenkinsfile</exclude>
            <exclude>**/.*</exclude>
            <exclude>**/*.adoc</exclude>
            <exclude>**/*.woff</exclude>
            <exclude>**/*.ttf</exclude>
            <exclude>**/*.woff2</exclude>
            <exclude>**/*.eot</exclude>
            <exclude>package-json.lock</exclude>
            <exclude>.tmp/**</exclude>
            <exclude>dist/**</exclude>
            <exclude>.tmp/**</exclude>
            <exclude>.vscode/**</exclude>
            <exclude>.*</exclude>
            <exclude>.*/**</exclude>
          </excludes>
        </configuration>
      </plugin>
```

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-12-01 01:27
## GPG Signature

* stable latest maven container image [`quay.io/gravitee-lab/cicd-maven`](https://quay.io/repository/gravitee-lab/cicd-maven?tab=tags) now successfully used to setup GPG identity to sign artifact, with Gravitee Bot GPG signature, with init / rotate standard operations on secrets : https://app.circleci.com/pipelines/github/gravitee-lab/GraviteeCiCdOrchestrator/808/workflows/46f2ab14-a9f9-4e73-918d-c07c280ce82d/jobs/570

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-12-02 07:41
## Trigger Release and Dry Run Release with a `curl`

* Trigger a dry run :

```bash
export CCI_TOKEN="<token value>"
export ORG_NAME="gravitee-lab"
export REPO_NAME="release"
export BRANCH="3.1.x"
export JSON_PAYLOAD="{

    \"branch\": \"${BRANCH}\",
    \"parameters\":

    {
        \"gio_action\": \"dry_release\"
    }

}"

curl -X POST -d "${JSON_PAYLOAD}" -H 'Content-Type: application/json' -H 'Accept: application/json' -H "Circle-Token: ${CCI_TOKEN}" https://circleci.com/api/v2/project/gh/${ORG_NAME}/${REPO_NAME}/pipeline
```

* Trigger a release :

```bash
export CCI_TOKEN="<token value>"
export ORG_NAME="gravitee-lab"
export REPO_NAME="release"
export BRANCH="3.1.x"
export JSON_PAYLOAD="{

    \"branch\": \"${BRANCH}\",
    \"parameters\":

    {
        \"gio_action\": \"release\"
    }

}"

curl -X POST -d "${JSON_PAYLOAD}" -H 'Content-Type: application/json' -H 'Accept: application/json' -H "Circle-Token: ${CCI_TOKEN}" https://circleci.com/api/v2/project/gh/${ORG_NAME}/${REPO_NAME}/pipeline

```

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-12-03 08:13
## Release Dry run process simplification (no gpg signing)

agreed: 
* for a dry run release, no GPG signing the maven artifacts, no java-doc inclusion and no source code inclusion in artifacts are done, only `mvn enforcer:enforce` and `mvn clean deploy (to private aritfactory)`
* note that this does not change anything from what what done in Jenkins, with the Jenkins Groovy Scripts, see for example ccc

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-12-03 08:20
# Release dry run tests with dependencies on https://github.com/gravitee-io Github Org

### Secrets management

* We have a problem with the Git SSH public and private keys of the Gravitee Bot (so we need to rotate those secrets) : 
```bash
~/someops$ secrethub read --out-file ".retrieved.ssh.cicd.graviteebot.id_rsa" graviteeio/cicd/graviteebot/git/ssh/private_key
~/someops$ chmod 600 .retrieved.ssh.cicd.graviteebot.id_rsa
~/someops$ ssh -Ti .retrieved.ssh.cicd.graviteebot.id_rsa git@github.com
key_load_public: invalid format
```

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-12-04 01:29
# One interesting facts about  CICD and pom.xml best practices during dev workflow

* in [this pipeline execution](https://app.circleci.com/pipelines/github/gravitee-io/gravitee-gateway/88/workflows/0f7aad37-8021-46cf-8509-fe53f5743d39/jobs/79), we can see : 
  * that the dev team added a maven profile to the pom.xml, in order to allow some dependencies (vertx related) to be  snapshots
  * the maven profile used is : 

```Xml
<project>

    <! -- ... -->

    <!-- allow snapshot only for vertx until the final release -->
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>1.4.1</version>
                    <configuration>
                        <rules>
                            <requireReleaseDeps>
                                <message>No Snapshots Allowed!</message>
                                <excludes>
                                    <exclude>io.vertx:*</exclude>
                                </excludes>
                            </requireReleaseDeps>
                            <requireReleaseVersion>
                                <message>No Snapshots Allowed!</message>
                            </requireReleaseVersion>
                        </rules>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
    <profiles>
        <profile>
            <id>allow-snapshots-for-swagger3</id>
            <activation><activeByDefault>true</activeByDefault></activation>
            <repositories>
                <repository>
                    <id>snapshots-repo</id>
                    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
                    <releases><enabled>false</enabled></releases>
                    <snapshots><enabled>true</enabled></snapshots>
                </repository>
            </repositories>
        </profile>
    </profiles>
</project>
```
  * this causes the dry run release process to fail, because the dry run consist in a maven profile, and the dry run does run the `mvn enforcer:enforce` goal
  * result is that the release dry run cannot be tested  until all SNAPSHOTS are removed from dependencies.  

_**One question : Vertx dependencies which are in `SNAPSHOT`, are coming from `gravitee-node`, am I right ?**_

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-12-04 01:47
# One proposition to make things clear (needs testing on gravitee-lab) 

The issue: When we launch a release dry run, what appearsin Circle CI web UI, next to all triggered pipelines, is the name of the CircleCI Workflow, which is currently, `release`. And it also is the casewhen a non-dry run release is launched.

I found a way to change that, without changing anything but the `.circleci/config.yml` Pipeline definition for all dev repos,to :+1: 

```Yaml
version: 2.1

parameters:
  gio_action:
    type: enum
    enum: [release, pr_build]
    default: pr_build
  dry_run:
    type: boolean
    default: true
    description: "Run in dry run mode?"
  maven_profile_id:
    type: string
    default: "gravitee-dry-run"
    description: "Maven ID of the Maven profile to use for a dry run ?"
  secrethub_org:
    type: string
    default: "gravitee-lab"
    description: "SecretHub Org to use to fetch secrets ?"
  secrethub_repo:
    type: string
    default: "cicd"
    description: "SecretHub Repo to use to fetch secrets ?"

orbs:
  gravitee: gravitee-io/gravitee@dev:1.0.2

workflows:
  version: 2.1
  pull_requests:
    when:
      equal: [ pr_build, << pipeline.parameters.gio_action >> ]
    jobs:
      - gravitee/pr-build:
          context: cicd-orchestrator
  release:
    # see https://circleci.com/docs/2.0/configuration-reference/#logic-statement-examples
    when:
      equal: [ release, << pipeline.parameters.gio_action >> ]
    when:
      and:
        - equal: [ release, << pipeline.parameters.gio_action >> ]
        - not: << pipeline.parameters.dry_run >>
    jobs:
      # return to simple definition :
      - gravitee/release:
          context: cicd-orchestrator
          dry_run: << pipeline.parameters.dry_run >>
          secrethub_org: << pipeline.parameters.secrethub_org >>
          secrethub_repo: << pipeline.parameters.secrethub_repo >>
          maven_profile_id: << pipeline.parameters.maven_profile_id >>
  release_dry_run:
    # see https://circleci.com/docs/2.0/configuration-reference/#logic-statement-examples
    when:
      equal: [ release, << pipeline.parameters.gio_action >> ]
    when:
      and:
        - equal: [ release, << pipeline.parameters.gio_action >> ]
        - << pipeline.parameters.dry_run >>
    jobs:
      # return to simple definition :
      - gravitee/release:
          context: cicd-orchestrator
          dry_run: << pipeline.parameters.dry_run >>
          secrethub_org: << pipeline.parameters.secrethub_org >>
          secrethub_repo: << pipeline.parameters.secrethub_repo >>
          maven_profile_id: << pipeline.parameters.maven_profile_id >>

```

**Comment by Jean-Baptiste-Lasselle** [comment] 2020-12-04 01:48
# Preparing an artifactory environment for the non dry run release process

In artifactory, the repo sued to depoy maven artifacts should be different for release, and dry run releases : 
* So I need to create the new  repo for the non-dry run release
* and also need to create a new `settings.xml` with all configuration for the non dry run release

**Comment by Jean-Baptiste-Lasselle** [comment] 2021-06-09 17:43
completed

**Closed by Jean-Baptiste-Lasselle** 2021-06-09 17:43 UTC
Labels: cicd
